import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

/**
 * Generates styles/tokens.css (CSS variables for the palette and the role
 * tokens, light and the ink theme) from tokens/sal.tokens.json.
 *
 *   bun scripts/tokens.ts          # write
 *   bun scripts/tokens.ts --check  # fail if tokens.css is stale
 */
export interface TokenFile {
  palette: Record<string, string>;
  radius: Record<string, string>;
  roles: Record<"light" | "dark", Record<string, string>>;
}

const root = join(import.meta.dirname, "..");

export const renderTokens = (tokens: TokenFile) => {
  const lines = [
    "/* Generated by scripts/tokens.ts from tokens/sal.tokens.json. Do not edit. */",
    ":root {",
    ...Object.entries(tokens.palette).map(
      ([name, value]) => `  --sal-${name}: ${value};`
    ),
    ...Object.entries(tokens.radius).map(
      ([name, value]) => `  --sal-radius-${name}: ${value};`
    ),
    ...Object.entries(tokens.roles.light).map(
      ([role, color]) => `  --${role}: var(--sal-${color});`
    ),
    "}",
    "",
    '/* The ink theme: only the "why" pages and the Open Call page. */',
    '[data-theme="dark"] {',
    ...Object.entries(tokens.roles.dark).map(
      ([role, color]) => `  --${role}: var(--sal-${color});`
    ),
    "}",
    "",
  ];
  return lines.join("\n");
};

if (import.meta.main) {
  const tokens = JSON.parse(
    await readFile(join(root, "tokens", "sal.tokens.json"), "utf8")
  ) as TokenFile;
  const css = renderTokens(tokens);
  const target = join(root, "styles", "tokens.css");

  if (process.argv.includes("--check")) {
    const current = await readFile(target, "utf8").catch(() => "");
    if (current !== css) {
      console.error(
        "styles/tokens.css is stale. Run `bun run --cwd packages/design-system tokens`."
      );
      process.exit(1);
    }
  } else {
    await writeFile(target, css);
  }
}
