import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

/**
 * Generates styles/tokens.css from the brand's own token file,
 * brand/tokens.json (SAL v4, binding): the palette, the nine role tokens for
 * light pages and ink pages, space, radii and the hairline.
 *
 *   bun scripts/tokens.ts          # write
 *   bun scripts/tokens.ts --check  # fail if tokens.css is stale
 */
interface Themed {
  dark: string;
  light: string;
}

export interface BrandTokens {
  color: { tokens: { name: string; value: string | Themed }[] };
  radius: { tokens: { name: string; value: string }[] };
  spacing: { tokens: { name: string; value: string }[] };
  stroke: { tokens: { name: string; value: string }[] };
}

/**
 * `rule` is a palette value in the brand (row hairlines on light pages); the
 * platform also needs it as a role so hairlines stay quiet on ink pages. Its
 * ink-page value is an existing tone: no colour is added.
 */
export const platformRoles: Record<string, Themed> = {
  rule: { dark: "{ink-70}", light: "{rule}" },
};

/** radius-key belongs to the retired round Key and is never emitted. */
const retired = new Set(["radius-key"]);

const REFERENCE = /^\{([a-z0-9-]+)\}$/;

const reference = (value: string) => {
  const match = REFERENCE.exec(value);
  if (!match) {
    throw new Error(`Role values must reference a palette colour: ${value}`);
  }
  return `var(--sal-${match[1]})`;
};

export const splitColors = (tokens: BrandTokens) => {
  const palette: Record<string, string> = {};
  const roles: Record<string, Themed> = {};
  for (const token of tokens.color.tokens) {
    if (typeof token.value === "string") {
      palette[token.name] = token.value;
    } else {
      roles[token.name] = token.value;
    }
  }
  return { palette, roles: { ...roles, ...platformRoles } };
};

export const renderTokens = (tokens: BrandTokens) => {
  const { palette, roles } = splitColors(tokens);
  const sizes = [
    ...tokens.spacing.tokens,
    ...tokens.radius.tokens,
    ...tokens.stroke.tokens,
  ].filter((token) => !retired.has(token.name));

  const lines = [
    "/* Generated by scripts/tokens.ts from brand/tokens.json. Do not edit. */",
    ":root {",
    ...Object.entries(palette).map(
      ([name, value]) => `  --sal-${name}: ${value};`
    ),
    ...sizes.map((token) => `  --sal-${token.name}: ${token.value};`),
    ...Object.entries(roles).map(
      ([role, value]) => `  --${role}: ${reference(value.light)};`
    ),
    "}",
    "",
    '/* The ink theme: only the "why" pages and the Open Call page. */',
    '[data-theme="dark"] {',
    ...Object.entries(roles).map(
      ([role, value]) => `  --${role}: ${reference(value.dark)};`
    ),
    "}",
    "",
  ];
  return lines.join("\n");
};

export const brandTokensPath = join(
  import.meta.dirname,
  "..",
  "..",
  "..",
  "brand",
  "tokens.json"
);

if (import.meta.main) {
  const tokens = JSON.parse(
    await readFile(brandTokensPath, "utf8")
  ) as BrandTokens;
  const css = renderTokens(tokens);
  const target = join(import.meta.dirname, "..", "styles", "tokens.css");

  if (process.argv.includes("--check")) {
    const current = await readFile(target, "utf8").catch(() => "");
    if (current !== css) {
      console.error(
        "styles/tokens.css is stale. Run `bun run --cwd packages/design-system tokens`."
      );
      process.exit(1);
    }
  } else {
    await writeFile(target, css);
  }
}
